### ISSUE TITLE
"Not Moose" explanation makes no sense

### ISSUE THREAD

**Issue by shadowcat-mst** [alexbyk/perl-evo#3]
https://metacpan.org/pod/Evo::Class#Why-not-OO-and-Moose-like

There are StrictConstructor extensions for both Moose and Moo so I don't understand why this couldn't've been written as an Import::Into bundle of existing software? (see Mew for a moderately complex example)

**Comment by alexbyk** [comment]
Thanks. You're right. The documentation wasn't very relevant. Fixed in https://github.com/alexbyk/perl-evo/commit/19247003993da8ba3687a4adb37114920bd41aca

About "why not just extend Moose". This module differs a lot from Moose. (It allows to use any references as objects (not only hashrefs), it doesn't uses perl's @ISA). So I decided to write all things from the scratch
