### ISSUE TITLE
Specifics about other implementations of promises

### ISSUE THREAD

**Issue by tm604** [alexbyk/perl-evo#4]
Hi,

The Evo::Promise documentation mentions this:

> Different implementations of promise should work together well by design. Right now there are other
> implementations in CPAN. But when I tested them(2016yr), they were far away from A+ and contained
> many bugs. So if need to mix different promise libraries, try to start the chain from this one

Details about the libraries you tested and the issues you encountered would be useful here - are the bugs new issues you found during testing, or existing entries in the bug tracker? Do you have examples of the sort of code you were trying to write and the problems you encountered?

Personally I'd recommend starting with Future, since it's [widely-used](https://metacpan.org/requires/distribution/Future?sort=[[2,1]]), has been around for a few years and does not enforce an event loop; however, it is intentionally not directly compatible with Promises/A. It does provide much better composition support than typical libraries - see needs_all / want_any / helper functions in Future::Utils::*.

cheers,

Tom

**Comment by alexbyk** [comment]
Hi. Thanks for you feedback.

1) Answering p1 requires a lot of time. In short: I used Promises.pm, found them not compatible with Spec/A+, made a code-review and decided to write it by my own. That's all I can provide right now.

Also Evo::Promise shouldn't be use directly. This module was designed to provide a promises role(mixin) for frameworks and libraries/loops. Maybe I din't mention it in docs because Evo is in early development state, but I have a little demo  [here](https://metacpan.org/pod/Mojo::Pua) 

2) I know about Future.pm (but thanks for the advice).

**Comment by tm604** [comment]
Mentioning Promises.pm by name would be enough, sure - at the moment it's just a bit vague, all I'd suggest is maybe a "SEE ALSO" section like this:

```
=head1 SEE ALSO

=over

=item * L<Promises> - based on, but not directly compatible (details?) with Spec/A+

=item * L<Future> - an alternative implementation

=back
```

Since the current text says "Different implementations of promise should work together well by design", it'd be helpful to explain how to do this with Evo::Promise and Promises/Future/other modules. If they _don't_ work together, then the text is slightly misleading =)

**Comment by alexbyk** [comment]
closed with https://github.com/alexbyk/perl-evo/commit/7376460b86ea38e2ecf733b46d02fa6152d84298 Thanks for a feedback
