### ISSUE TITLE
Compilation error (freebsd 10, perl 5.25.10)

### ISSUE THREAD

**Issue by eserte** [alexbyk/perl-evo#5]
In my smoker zoo there's only one combination where the compilation of Evo-0.0308 fails:
```
cc -c  -I./  -std=c99 -Wall -Wextra -Werror -W -O2    -DVERSION=\"0.0308\"  -DXS_VERSION=\"0.0308\" -DPIC -fPIC "-I/usr/perl5.25.10p/lib/5.25.10/amd64-freebsd/CORE"   lib/Evo/Class/Attrs/XS.c -o lib/Evo/Class/Attrs/XS.o
In file included from lib/Evo/Class/Attrs/XS.xs:3:
In file included from /usr/perl5.25.10p/lib/5.25.10/amd64-freebsd/CORE/perl.h:5779:
/usr/perl5.25.10p/lib/5.25.10/amd64-freebsd/CORE/inline.h:1683:1: error: unused function 'Perl_foldEQ_latin1' [-Werror,-Wunused-function]
Perl_foldEQ_latin1(const char *s1, const char *s2, I32 len)
^
/usr/perl5.25.10p/lib/5.25.10/amd64-freebsd/CORE/inline.h:1716:1: error: unused function 'Perl_foldEQ_locale' [-Werror,-Wunused-function]
Perl_foldEQ_locale(const char *s1, const char *s2, I32 len)
^
2 errors generated.
*** Error code 1
```
This is a freebsd 10.3 system, default compiler is clang 3.4.1, with perl 5.25.10. There are no compile problems on the same system up to perl 5.25.9. And on the same system it compiled fine with gcc + perl 5.25.10. Other systems (freebsd 9, various linux distributions, Mac OS X) have no problems.

**Comment by alexbyk** [comment]
Thanks for the report.

As far as I can see this is a perl's source code issue. I can be wrong, but I'm closing it anyway because I'm going to spend next couple of days skiing and traveling. If I don't close it now I'll have a feeling that I left something important behind and that can interrupt me from having a good time. And when I'm back, there are high chances it'll be solved by someone else/something else. Even if it looks like I'm closing my eyes and pretending that nothing happens, it's still a better strategy than doing nothing.

**Comment by eserte** [comment]
Looking at perl commit 0f9cb40cba19106bb8ef1437d9d4966f6e6d2d44, it seems you're right.

Happy skiing!
